version: '3.8'

services:
  app:
    build: .
    container_name: orcamento-app
    ports:
      - "8082:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      orcamento_db:
        condition: service_healthy
    networks:
      - orcamento_network

  orcamento_db:
    container_name: orcamento_db
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: orcamento_db
      MYSQL_ROOT_PASSWORD: 'health'
    ports:
      - '3307:3306'
    networks:
      - orcamento_network
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      start_period: 5s
      interval: 1s
      timeout: 5s
      retries: 15

networks:
  orcamento_network:
    driver: bridge

volumes:
  mysql:
